// Generated by CoffeeScript 1.4.0
(function() {
  var Runner, deepEqual, entry, forEach, fs, loadTest, normalizePath, path, _ref;

  Runner = require('./runner');

  fs = require('fs');

  path = require('path');

  _ref = require('./util'), deepEqual = _ref.deepEqual, forEach = _ref.forEach;

  require('coffee-script');

  normalizePath = function(dirPath, filePath) {
    var fullPath;
    fullPath = path.resolve(path.join(dirPath, filePath));
    return path.join(path.dirname(fullPath), path.basename(filePath, path.extname(filePath)));
  };

  entry = function(dirPath) {
    var helper, runner;
    runner = new Runner();
    helper = function(filePath, next) {
      return loadTest(runner, normalizePath(dirPath, filePath), next);
    };
    return fs.readdir(dirPath, function(err, files) {
      return forEach(files, helper, function(err, res) {
        if (err) {
          return console.log("fail load:", err);
        } else {
          return runner.run(function(err, res) {
            return console.log("result: ", err, res);
          });
        }
      });
    });
  };

  loadTest = function(runner, filePath, next) {
    var moduleFunc;
    moduleFunc = require(filePath);
    if (!(moduleFunc instanceof Function)) {
      return next(new Error("module " + filePath + " not export a function"));
    } else {
      try {
        moduleFunc(runner);
        return next(null);
      } catch (e) {
        return next(e);
      }
    }
  };

  module.exports = entry;

}).call(this);
