// Generated by CoffeeScript 1.4.0
(function() {
  var Runner, entry, fs, loadTest, normalizePath, path, util;

  Runner = require('./runner');

  fs = require('fs');

  path = require('path');

  util = require('./util');

  require('coffee-script');

  normalizePath = function(dirPath, filePath) {
    var fullPath;
    fullPath = path.resolve(path.join(dirPath, filePath));
    return path.join(path.dirname(fullPath), path.basename(filePath, path.extname(filePath)));
  };

  entry = function(dirPath) {
    var helper, runner;
    runner = new Runner();
    helper = function(filePath, next) {
      return loadTest(runner, normalizePath(dirPath, filePath), next);
    };
    return fs.readdir(dirPath, function(err, files) {
      return util.forEach(files, helper, function(err, res) {
        if (err) {
          return console.log("test.fail.load:", err);
        } else {
          console.log('runner.torun');
          return runner.run(function(err, res) {
            return console.log("result: ", err, res);
          });
        }
      });
    });
  };

  loadTest = function(runner, filePath, next) {
    try {
      util.require(filePath, {
        test: runner
      });
      return next(null);
    } catch (e) {
      return next(e);
    }
  };

  module.exports = entry;

}).call(this);
