// Generated by CoffeeScript 1.4.0
(function() {
  var Runner, Suite, SuiteResult, Test, TestResult, deepEqual, forEach, _ref,
    __slice = [].slice;

  _ref = require('./util'), deepEqual = _ref.deepEqual, forEach = _ref.forEach;

  TestResult = require('./test-result');

  SuiteResult = require('./suite-result');

  Test = require('./test');

  Suite = require('./suite');

  Runner = (function() {

    function Runner(timeout) {
      this.timeout = timeout != null ? timeout : 2000;
      this.suites = [];
      this.name = "All Tests";
      this.innerLogs = [];
    }

    Runner.prototype.add = function(name, func) {
      var prevSuite, suite;
      suite = new Suite(this, name, func);
      this.suites.push(suite);
      prevSuite = this.currentSuite;
      this.currentSuite = suite;
      try {
        return this.currentSuite["eval"]();
      } finally {
        this.currentSuite = prevSuite;
      }
    };

    Runner.prototype.it = function(name, func) {
      if (!this.currentSuite) {
        throw new Error("test.do must be called within test.add");
      }
      return this.currentSuite.add(new Test(this, name, func));
    };

    Runner.prototype.ok = function(val, msg) {
      var err, res;
      if (msg == null) {
        msg = "ok(" + val + ")";
      }
      err = new Error(msg);
      if (!val) {
        err.expected = true;
        err.actual = val;
        throw err;
      } else if (val instanceof Function) {
        res = val();
        if (!res) {
          err.expected = true;
          err.actual = res;
          throw err;
        }
      }
    };

    Runner.prototype.equal = function(lhs, rhs, msg) {
      var err;
      if (msg == null) {
        msg = "" + lhs + " == " + rhs;
      }
      if (!deepEqual(lhs, rhs)) {
        err = new Error(msg);
        err.expected = rhs;
        err.actual = lhs;
        throw err;
      }
    };

    Runner.prototype.throws = function(lhs, msg) {
      var err;
      if (msg == null) {
        msg = "" + lhs + " expect to throw";
      }
      try {
        lhs();
        err = new Error(msg);
        err.expected = "throws";
        err.actual = "no throw";
        throw err;
      } catch (e) {

      }
    };

    Runner.prototype.isa = function(lhs, rhs, msg) {
      var err;
      if (msg == null) {
        msg = "" + lhs + " typeof " + rhs;
      }
      err = new Error(msg);
      err.expected = rhs;
      if (typeof rhs === 'string') {
        if (!typeof lhs === rhs) {
          err.actual = typeof lhs;
          throw err;
        }
      } else {
        if (!lhs instanceof rhs) {
          err.actual = false;
          throw err;
        }
      }
    };

    Runner.prototype.run = function(cb) {
      var cases, helper, result;
      result = new SuiteResult(this);
      cases = [].concat(this.suites);
      helper = function(test, next) {
        return test.run(function(err, res) {
          if (err) {
            return next(err);
          } else {
            result.push(res);
            return next(null, result);
          }
        });
      };
      return forEach(cases, helper, function(err, res) {
        return cb(err, result);
      });
    };

    Runner.prototype.log = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return this.innerLogs.push(args);
    };

    Runner.prototype.resetLog = function() {
      var logs;
      logs = this.innerLogs;
      this.innerLogs = [];
      return logs;
    };

    return Runner;

  })();

  module.exports = Runner;

}).call(this);
