// Generated by CoffeeScript 1.4.0
(function() {
  var Test, TestResult, timeoutCallback;

  TestResult = require('./test-result');

  timeoutCallback = function(timeout, cb, timeoutCB) {
    var beforeTimeout, obj, whenTimeout;
    obj = {
      id: null,
      timedOut: false
    };
    whenTimeout = function() {
      obj.timedOut = true;
      clearTimeout(obj.id);
      return timeoutCB();
    };
    beforeTimeout = function() {
      if (!obj.timedOut) {
        clearTimeout(obj.id);
        return cb.apply(this, arguments);
      }
    };
    obj.id = setTimeout(whenTimeout, timeout);
    return beforeTimeout;
  };

  Test = (function() {

    function Test(runner, name, func) {
      this.runner = runner;
      this.name = name;
      this.func = func;
      this.async = this.func && this.func.length;
      this.timeout = this.runner.timeout || 2000;
    }

    Test.prototype.run = function(next) {
      var callback, result,
        _this = this;
      callback = timeoutCallback(this.timeout, next, function() {
        return next(null, new TestResult(_this, _this.runner.resetLog(), new Error("timeout " + _this.timeout + " msec exceeded.")));
      });
      if (this.async) {
        try {
          return this.func(function(err, res) {
            var result;
            console.log('Test.async.afterRun', _this.name);
            result = err ? new TestResult(_this, _this.runner.resetLog(), err) : new TestResult(_this, _this.runner.resetLog());
            return callback(null, result);
          });
        } catch (e) {
          console.log('Test.error', this.name);
          return callback(null, new TestResult(this, this.runner.resetLog(), e));
        }
      } else {
        result = (function() {
          try {
            this.func();
            return new TestResult(this, this.runner.resetLog());
          } catch (e) {
            return new TestResult(this, this.runner.resetLog(), e);
          }
        }).call(this);
        return callback(null, result);
      }
    };

    return Test;

  })();

  module.exports = Test;

}).call(this);
